[versions]
jackson = "2.21.0"
javalin = "6.7.0"
jslt = "0.1.14"
jsonSchemaValidator = "1.5.7"
palantirJavaFormat = "2.78.0"
slf4j = "2.0.16"
snakeyaml = "2.3"

# Test
assertj = "3.27.6"
junit = "5.11.4"
junitPlatform = "1.11.4"
mockito = "5.15.2"
logback = "1.5.16"

[libraries]
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { group = "com.fasterxml.jackson.dataformat", name = "jackson-dataformat-yaml", version.ref = "jackson" }
javalin = { group = "io.javalin", name = "javalin", version.ref = "javalin" }
jslt = { group = "com.schibsted.spt.data", name = "jslt", version.ref = "jslt" }
json-schema-validator = { group = "com.networknt", name = "json-schema-validator", version.ref = "jsonSchemaValidator" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeyaml" }

# Test
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
